name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test-terraform:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # Checkout code
      # ------------------------
      - name: Checkout
        uses: actions/checkout@v4

      # ------------------------
      # Node.js section
      # ------------------------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      # ------------------------
      # Terraform section
      # ------------------------
      



      # Init
      - name: Terraform Init
        working-directory: terraform/environments/dev    # adjust if needed
        run: terraform init -backend=false

      # Validate
      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate

      # Plan (safe, no apply)
      - name: Terraform Plan
        working-directory: terraform/environments/dev
        run: terraform plan -input=false

